### ISSUE TITLE
Mirror is broken

### ISSUE THREAD

**Issue by noliveleger** [mirror-effect-plus-protocol/mepp-web#34]
Cannot open mirror from admin for from client app 

Console displays one warning and one error: 

```
It looks like you wrote useEffect(async () => ...) or returned a Promise. Instead, write the async function inside your effect and call it immediately:

useEffect(() => {
  async function fetchData() {
    // You can await here
    const response = await MyAPI.getData(someId);
    // ...
  }
  fetchData();
}, [someId]); // Or [] if effect doesn't need props or state

Learn more about data fetching with Hooks: https://reactjs.org/link/hooks-data-fetching
    at ExerciseProvider (http://mepp.local:9090/main.js:305763:5)
    at MirrorPage (http://mepp.local:9090/main.js:313369:81)
    at WithPermissions (http://mepp.local:9090/main.js:146379:28)
    at div
    at Main (http://mepp.local:9090/main.js:309885:89)
    at Authenticated (http://mepp.local:9090/main.js:146288:28)
    at withAuth (http://mepp.local:9090/main.js:309872:23)
    at main
    at Main (http://mepp.local:9090/main.js:309988:79)
    at OverlayProvider (http://mepp.local:9090/main.js:309666:5)
    at withPage
    at RenderedRoute (http://mepp.local:9090/main.js:237841:5)
    at Routes (http://mepp.local:9090/main.js:238364:5)
    at CoreAdminRoutes (http://mepp.local:9090/main.js:154500:86)
    at RenderedRoute (http://mepp.local:9090/main.js:237841:5)
    at Routes (http://mepp.local:9090/main.js:238364:5)
    at CoreAdminUI (http://mepp.local:9090/main.js:154571:20)
    at div
    at http://mepp.local:9090/main.js:1888:73
    at ScopedCssBaseline (http://mepp.local:9090/main.js:47448:86)
    at AdminUI (http://mepp.local:9090/main.js:169166:27)
    at ThemeProvider (http://mepp.local:9090/main.js:68084:5)
    at ThemeProvider (http://mepp.local:9090/main.js:71037:5)
    at ThemeProvider (http://mepp.local:9090/main.js:65289:14)
    at ThemeProvider (http://mepp.local:9090/main.js:186608:23)
    at ResourceDefinitionContextProvider (http://mepp.local:9090/main.js:154815:17)
    at NotificationContextProvider (http://mepp.local:9090/main.js:164696:23)
    at I18nContextProvider (http://mepp.local:9090/main.js:162517:17)
    at Router (http://mepp.local:9090/main.js:238296:15)
    at HistoryRouter (http://mepp.local:9090/main.js:165326:23)
    at InternalRouter (http://mepp.local:9090/main.js:165243:23)
    at BasenameContextProvider (http://mepp.local:9090/main.js:165297:23)
    at AdminRouter (http://mepp.local:9090/main.js:165232:22)
    at QueryClientProvider (http://mepp.local:9090/main.js:234940:21)
    at PreferencesEditorContextProvider (http://mepp.local:9090/main.js:164948:23)
    at StoreContextProvider (http://mepp.local:9090/main.js:165791:20)
    at CoreAdminContext (http://mepp.local:9090/main.js:154439:30)
    at AdminContext (http://mepp.local:9090/main.js:169111:20)
    at Admin (http://mepp.local:9090/main.js:194280:30)
    at _default
    at Ge (http://mepp.local:9090/main.js:276722:17011)
    at StyledEngineProvider (http://mepp.local:9090/main.js:68377:5)
    at App (http://mepp.local:9090/main.js:310469:58)
```

```
Uncaught (in promise) TypeError: L.get is not a function
    at ue (deepar.esm.js:1:1)
    at s (deepar.esm.js:1:1)
    at deepar.wasm:0x6a4c7
    at deepar.wasm:0x2efdb
    at deepar.wasm:0x80cdf
    at te (deepar.esm.js:1:1)
    at ya (deepar.esm.js:1:1)
    at e (deepar.esm.js:1:1)
    at e (deepar.esm.js:1:1)
    at n (deepar.esm.js:1:1)
ue @ deepar.esm.js:1
s @ deepar.esm.js:1
$func2383 @ deepar.wasm:0x6a4c7
$func1334 @ deepar.wasm:0x2efdb
$rg @ deepar.wasm:0x80cdf
te @ deepar.esm.js:1
ya @ deepar.esm.js:1
e @ deepar.esm.js:1
e @ deepar.esm.js:1
n @ deepar.esm.js:1
Promise.then (async)
e @ deepar.esm.js:1
(anonymous) @ Player.jsx:55
commitHookEffectListMount @ react-dom.development.js:23150
commitPassiveMountOnFiber @ react-dom.development.js:24931
commitPassiveMountEffects_complete @ react-dom.development.js:24891
commitPassiveMountEffects_begin @ react-dom.development.js:24878
commitPassiveMountEffects @ react-dom.development.js:24866
flushPassiveEffectsImpl @ react-dom.development.js:27039
flushPassiveEffects @ react-dom.development.js:26984
(anonymous) @ react-dom.development.js:26769
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
run @ setImmediate.js:40
runIfPresent @ setImmediate.js:69
onGlobalMessage @ setImmediate.js:109
postMessage (async)
registerImmediate @ setImmediate.js:120
setImmediate @ setImmediate.js:27
schedulePerformWorkUntilDeadline @ scheduler.development.js:564
requestHostCallback @ scheduler.development.js:588
unstable_scheduleCallback @ scheduler.development.js:441
scheduleCallback$1 @ react-dom.development.js:27537
ensureRootIsScheduled @ react-dom.development.js:25683
scheduleUpdateOnFiber @ react-dom.development.js:25531
dispatchSetState @ react-dom.development.js:17527
handleTokens @ withAuth.jsx:60
await in handleTokens (async)
(anonymous) @ withAuth.jsx:63
commitHookEffectListMount @ react-dom.development.js:23150
commitPassiveMountOnFiber @ react-dom.development.js:24931
commitPassiveMountEffects_complete @ react-dom.development.js:24891
commitPassiveMountEffects_begin @ react-dom.development.js:24878
commitPassiveMountEffects @ react-dom.development.js:24866
flushPassiveEffectsImpl @ react-dom.development.js:27039
flushPassiveEffects @ react-dom.development.js:26984
(anonymous) @ react-dom.development.js:26769
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
run @ setImmediate.js:40
runIfPresent @ setImmediate.js:69
onGlobalMessage @ setImmediate.js:109
postMessage (async)
registerImmediate @ setImmediate.js:120
setImmediate @ setImmediate.js:27
schedulePerformWorkUntilDeadline @ scheduler.development.js:564
performWorkUntilDeadline @ scheduler.development.js:538
run @ setImmediate.js:40
runIfPresent @ setImmediate.js:69
onGlobalMessage @ setImmediate.js:109
postMessage (async)
registerImmediate @ setImmediate.js:120
setImmediate @ setImmediate.js:27
schedulePerformWorkUntilDeadline @ scheduler.development.js:564
requestHostCallback @ scheduler.development.js:588
unstable_scheduleCallback @ scheduler.development.js:441
scheduleCallback$1 @ react-dom.development.js:27537
ensureRootIsScheduled @ react-dom.development.js:25683
scheduleUpdateOnFiber @ react-dom.development.js:25531
dispatchSetState @ react-dom.development.js:17527
(anonymous) @ index.js:737
call @ index.js:736
applyTx @ index.js:455
push @ index.js:486
(anonymous) @ index.js:399
onCheckCameraPermission @ Intro.jsx:82
await in onCheckCameraPermission (async)
callCallback @ react-dom.development.js:4164
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:4291
executeDispatch @ react-dom.development.js:9041
processDispatchQueueItemsInOrder @ react-dom.development.js:9073
processDispatchQueue @ react-dom.development.js:9086
dispatchEventsForPlugins @ react-dom.development.js:9097
(anonymous) @ react-dom.development.js:9288
batchedUpdates$1 @ react-dom.development.js:26140
batchedUpdates @ react-dom.development.js:3991
dispatchEventForPluginEventSystem @ react-dom.development.js:9287
dispatchEventWithEnableCapturePhaseSelectiveHydrationWithoutDiscreteEventReplay @ react-dom.development.js:6465
dispatchEvent @ react-dom.development.js:6457
dispatchDiscreteEvent @ react-dom.development.js:6430
deepar.esm.js:1 DeepAR not yet initialized.
```

**Comment by fperreault** [comment]
fixed
